### Base URL Vercel: https://backend-filmes03mcpedrootavio.vercel.app

### 1. Buscar todos os filmes
GET https://backend-filmes03mcpedrootavio.vercel.app/filmes

###

### 2. Cadastrar um novo filme
POST https://backend-filmes03mcpedrootavio.vercel.app/filmes
Content-Type: application/json

{
  "titulo": "Matrix",
  "genero": "Ação",
  "classificacao_indicativa": "14 anos",
  "duracao": 136
}

###

### 3. Cadastrar - O Rei Leão
POST https://backend-filmes03mcpedrootavio.vercel.app/filmes
Content-Type: application/json

{
  "titulo": "O Rei Leão",
  "genero": "Animação",
  "classificacao_indicativa": "Livre",
  "duracao": 88
}

###

### 4. Cadastrar - Vingadores: Ultimato
POST https://backend-filmes03mcpedrootavio.vercel.app/filmes
Content-Type: application/json

{
  "titulo": "Vingadores: Ultimato",
  "genero": "Ação",
  "classificacao_indicativa": "12 anos",
  "duracao": 181
}

###

### 5. Cadastrar - Divertida Mente
POST https://backend-filmes03mcpedrootavio.vercel.app/filmes
Content-Type: application/json

{
  "titulo": "Divertida Mente",
  "genero": "Animação",
  "classificacao_indicativa": "Livre",
  "duracao": 95
}

###

### 6. Editar / Atualizar um filme pelo ID (Substitua o 1 pelo ID desejado)
PUT https://backend-filmes03mcpedrootavio.vercel.app/filmes/1
Content-Type: application/json

{
  "titulo": "Motoqueiro Fantasma: Espírito de Vingança",
  "genero": "Ação / Fantasia",
  "classificacao_indicativa": "14 anos",
  "duracao": 95
}

###

### 7. Deletar um filme pelo ID (Substitua o 1 pelo ID desejado)
DELETE https://backend-filmes03mcpedrootavio.vercel.app/filmes/1

###

### 8. Buscar apenas filmes de Ação
GET https://backend-filmes03mcpedrootavio.vercel.app/filmes/acao

###

### 9. Buscar apenas filmes com classificação Livre
GET https://backend-filmes03mcpedrootavio.vercel.app/filmes/livre